package daycare.gui;

import daycare.console.DayCare;
import daycare.entity.DayCareRatioRule;
import daycare.entity.ImmunizationType;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

public class VaccineManageWindows {
    private JTable vaccineTable;
    private JButton removeButton;
    private JButton addVaccineButton;
    private JTextField vaccineIdText;
    private JTextField vaccineNameText;
    private JTextField minDoeseText;
    private JTextField injectIntervalText;
    private JPanel vaccineManagePanel;
    private DayCare dayCare;

//    public static void main(String[] args) {
//        DayCare dayCare = new DayCare();
//        dayCare.demo();
//        new VaccineManageWindows(dayCare);
//    }

    public void updateVacineList() {
        String vaccineColumns[] = {"Vaccine ID", "Vaccine Name", "MiniDoses", "Inject Interval"};
        List<ImmunizationType> list = dayCare.getTypes();
        int rowLength = list.size();
        int columnsLength = vaccineColumns.length;
        String[][] data = new String[rowLength][columnsLength];
        for (int j = 0; j < list.size(); j++) {
            ImmunizationType vaccine = list.get(j);
            data[j][0] = String.valueOf(vaccine.getVaccineID());
            data[j][1] = vaccine.getVaccineName();
            data[j][2] = String.valueOf(vaccine.getMinDoses());
            data[j][3] = vaccine.getInjectInterval().toString();
        }
        DefaultTableModel tableModel = new DefaultTableModel(data, vaccineColumns);
        vaccineTable.setModel(tableModel);

    }

    public void addVaccine() {
        ImmunizationType type = new ImmunizationType();
        type.setVaccineID(Integer.valueOf(vaccineIdText.getText()));
        type.setVaccineName(vaccineNameText.getText());
        List<Integer> list = new ArrayList<>();
        for (String s : injectIntervalText.getText().strip().split(",")) {
            list.add(Integer.valueOf(s));
        }
        type.setInjectInterval(list);
        type.setMinDoses(Integer.valueOf(minDoeseText.getText()));
        dayCare.addVaccine(type);
    }

    public void fillId() {
        int size = dayCare.getTypes().size();
        vaccineIdText.setText(String.valueOf(dayCare.getTypes().get(size - 1).getVaccineID() + 1));
    }

    public void listenerSetup() {
        removeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int row = vaccineTable.getSelectedRow();
                if (row != -1) {
                    int vaccineId = Integer.valueOf((String) vaccineTable.getValueAt(row, 0));
                    dayCare.removeVaccineById(vaccineId);
                    updateVacineList();
                }

            }
        });
        addVaccineButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addVaccine();
                fillId();
                updateVacineList();
            }
        });
    }

    public VaccineManageWindows(DayCare dayCare) {
        this.dayCare = dayCare;
        JFrame jFrame = new JFrame();
        jFrame.setTitle("Vaccine Manage");
        jFrame.setContentPane(vaccineManagePanel);
        jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jFrame.pack();
        jFrame.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        jFrame.setLocation(dim.width / 2 - vaccineManagePanel.getSize().width / 2, dim.height / 2 - vaccineManagePanel.getSize().height / 2);
        jFrame.setResizable(false);
        vaccineTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        updateVacineList();
        fillId();
        listenerSetup();

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        vaccineManagePanel = new JPanel();
        vaccineManagePanel.setLayout(new GridBagLayout());
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setMinimumSize(new Dimension(200, 300));
        scrollPane1.setOpaque(true);
        scrollPane1.setPreferredSize(new Dimension(300, 200));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridheight = 10;
        gbc.fill = GridBagConstraints.BOTH;
        vaccineManagePanel.add(scrollPane1, gbc);
        vaccineTable = new JTable();
        vaccineTable.setAutoResizeMode(0);
        scrollPane1.setViewportView(vaccineTable);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vaccineManagePanel.add(spacer1, gbc);
        removeButton = new JButton();
        removeButton.setText("remove");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vaccineManagePanel.add(removeButton, gbc);
        vaccineIdText = new JTextField();
        vaccineIdText.setMinimumSize(new Dimension(150, 30));
        vaccineIdText.setPreferredSize(new Dimension(150, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vaccineManagePanel.add(vaccineIdText, gbc);
        vaccineNameText = new JTextField();
        vaccineNameText.setMinimumSize(new Dimension(150, 30));
        vaccineNameText.setPreferredSize(new Dimension(150, 30));
        vaccineNameText.setText("Covid-19 Vaccine");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vaccineManagePanel.add(vaccineNameText, gbc);
        minDoeseText = new JTextField();
        minDoeseText.setMinimumSize(new Dimension(150, 30));
        minDoeseText.setPreferredSize(new Dimension(150, 30));
        minDoeseText.setText("2");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vaccineManagePanel.add(minDoeseText, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Vaccine ID: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        vaccineManagePanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Vaccine Name: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        vaccineManagePanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Min doese: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        vaccineManagePanel.add(label3, gbc);
        injectIntervalText = new JTextField();
        injectIntervalText.setMinimumSize(new Dimension(150, 30));
        injectIntervalText.setPreferredSize(new Dimension(150, 30));
        injectIntervalText.setText("10,30");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vaccineManagePanel.add(injectIntervalText, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Inject Interval: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        vaccineManagePanel.add(label4, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        vaccineManagePanel.add(spacer2, gbc);
        addVaccineButton = new JButton();
        addVaccineButton.setText("add vaccine");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 9;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vaccineManagePanel.add(addVaccineButton, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 13;
        gbc.fill = GridBagConstraints.VERTICAL;
        vaccineManagePanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        vaccineManagePanel.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vaccineManagePanel.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        vaccineManagePanel.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        vaccineManagePanel.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        vaccineManagePanel.add(spacer8, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        vaccineManagePanel.add(spacer9, gbc);
        final JPanel spacer10 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        vaccineManagePanel.add(spacer10, gbc);
        final JPanel spacer11 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        vaccineManagePanel.add(spacer11, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return vaccineManagePanel;
    }

}
